server:
  port: 8021
spring:
  application:
    name: TestSpringSecurity
  datasource:
    url: jdbc:mysql://localhost:3306/sc?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #redis配置
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password: 123456
    timeout: 10s
mybatis-plus:
  type-aliases-package: com.lqj.entity
  mapper-locations: classpath:**/xml/*.xml
  configuration:
    jdbc-type-for-null: null
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html